# Generated by Django 5.0 on 2023-12-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toddoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1234-04-12'),
            preserve_default=False,
        ),
    ]
